### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by colepizzarella** [TimLuq/node-spigot-bridge#1]
What is the status of this? Is it working?

I've built and attempted to create a plugin in the node-plugins folder as per the setup instructions via a local npm module; however, I receive an error of "Cannot find module: ./node_modules/test-plugin/dist/test.js"

I've also tried placing the module directly into the "plugins/NodeSpigotBridge/node_modules" as well as updating the package.json there with no luck. It seems to fix the pathing issue, but then an error of "cannot find module spigot-bridge" occurs.

If this is in a working state, could you possibly make an example of a working repo?

**Comment by TimLuq** [comment]
It works, yes. But still lacking a lot of APIs. I'm working on a version for 1.13 that requires `node >= 10.5` which should be better in some ways (such as thread isolation of plugins and live API calls between modules that exposes them) as well as support a few more APIs (such as material and block manipulation).

The default path for plugins is relative to the working directory of the java process, not to the plugin directory. This means that the `spigot/node-plugins` directory is a sibling to the normal `spigot/plugins`. The full path for the `package.json` of `test-plugin` should be `spigot/node-plugins/node_modules/test-plugin/package.json` - this might be the reason why it fails to load the plugin.

After the version for 1.13 is released I'll also release some plugins. This may take a couple of months though, since I currently don't have a lot of free time.
